In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
y_train[:3]

array([[6],
       [9],
       [9]], dtype=uint8)

In [5]:
y_train = y_train.reshape(-1 , )
y_test = y_test.reshape(-1 , )

In [6]:
y_train[:3]

array([6, 9, 9], dtype=uint8)

In [7]:
x_train = x_train/255
x_test = x_test/255

In [8]:
y_train_one_hot_encoded = keras.utils.to_categorical(y_train , num_classes=10 , dtype="float32")

In [9]:
y_test_one_hot_encoded = keras.utils.to_categorical(y_test , num_classes=10 , dtype="float32")

In [10]:
y_train_one_hot_encoded[:3]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [9]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape = (32,32,3)),
    keras.layers.Dense(3000 , activation = "relu"),
    keras.layers.Dense(1000 , activation = "relu"),
    keras.layers.Dense(10 , activation="sigmoid")
])

model.compile(optimizer="SGD" , loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(x_train , y_train_one_hot_encoded , epochs=50)

Epoch 1/50
1563/1563 [==============================] - 17s 9ms/step - loss: 1.8091 - accuracy: 0.3561
Epoch 2/50
1563/1563 [==============================] - 14s 9ms/step - loss: 1.6248 - accuracy: 0.4280
Epoch 3/50
1563/1563 [==============================] - 14s 9ms/step - loss: 1.5422 - accuracy: 0.4554
Epoch 4/50
1563/1563 [==============================] - 14s 9ms/step - loss: 1.4810 - accuracy: 0.4796
Epoch 5/50
1563/1563 [==============================] - 19s 12ms/step - loss: 1.4337 - accuracy: 0.4947
Epoch 6/50
1563/1563 [==============================] - 14s 9ms/step - loss: 1.3895 - accuracy: 0.5094
Epoch 7/50
1563/1563 [==============================] - 15s 10ms/step - loss: 1.3517 - accuracy: 0.5243
Epoch 8/50
1563/1563 [==============================] - 16s 10ms/step - loss: 1.3151 - accuracy: 0.5390
Epoch 9/50
1563/1563 [==============================] - 15s 10ms/step - loss: 1.2841 - accuracy: 0.5491
Epoch 10/50
1563/1563 [==============================] - 16s 10ms/ste

In [10]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [11]:
def get_model():
    model = keras.Sequential([
    keras.layers.Flatten(input_shape = (32,32,3)),
    keras.layers.Dense(3000 , activation = "relu"),
    keras.layers.Dense(1000 , activation = "relu"),
    keras.layers.Dense(10 , activation="sigmoid")
    ])

    model.compile(optimizer="SGD" , loss="categorical_crossentropy", metrics=["accuracy"])
    return model

In [18]:
model.evaluate(x_test ,y_test_one_hot_encoded )

313/313 [==============================] - 3s 5ms/step - loss: 1.8381 - accuracy: 0.5231


[1.838140845298767, 0.5231000185012817]

In [20]:
np.argmax(model.predict(x_test)[0])

313/313 [==============================] - 1s 3ms/step


3

In [22]:
y_test[0]

array([3], dtype=uint8)

In [12]:
import time

In [14]:
t1 = time.time()
with tf.device("GPU:0"):
    model1 = get_model()
    model1.fit(x_train , y_train_one_hot_encoded , epochs=5)
t2 = time.time()
print((t2-t1))

Epoch 1/5
1563/1563 [==============================] - 15s 9ms/step - loss: 1.8101 - accuracy: 0.3544
Epoch 2/5
1563/1563 [==============================] - 14s 9ms/step - loss: 1.6245 - accuracy: 0.4255
Epoch 3/5
1563/1563 [==============================] - 14s 9ms/step - loss: 1.5425 - accuracy: 0.4576
Epoch 4/5
1563/1563 [==============================] - 14s 9ms/step - loss: 1.4826 - accuracy: 0.4771
Epoch 5/5
1563/1563 [==============================] - 14s 9ms/step - loss: 1.4325 - accuracy: 0.4946
72.96538925170898


In [16]:
t1 = time.time()
with tf.device("CPU:0"):
    model1 = get_model()
    model1.fit(x_train , y_train_one_hot_encoded , epochs=1)
t2 = time.time()
print((t2-t1))

1563/1563 [==============================] - 67s 42ms/step - loss: 1.8082 - accuracy: 0.3554
67.98110342025757


In [28]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

# CNN

In [11]:
model = keras.Sequential([
        #Convolution
        keras.layers.Conv2D(filters = 30 , kernel_size = (3,3) , activation = "relu" ,input_shape = (32,32,3) ),
        keras.layers.MaxPool2D((2,2),),
        keras.layers.Conv2D(filters = 30 , kernel_size = (3,3) , activation = "relu" ),
        keras.layers.MaxPool2D((2,2),),
        #ANN
        keras.layers.Flatten(),
        keras.layers.Dense(30 , activation = "relu"),
        keras.layers.Dense(10 , activation="softmax")
        ])

model.compile(optimizer="adam" , loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        

In [12]:
model.fit(x_train , y_train , epochs=10)

Epoch 1/10
1563/1563 [==============================] - 36s 14ms/step - loss: 1.6224 - accuracy: 0.4082
Epoch 2/10
1563/1563 [==============================] - 26s 17ms/step - loss: 1.2706 - accuracy: 0.5488
Epoch 3/10
1563/1563 [==============================] - 13s 8ms/step - loss: 1.1363 - accuracy: 0.6028
Epoch 4/10
1563/1563 [==============================] - 23s 15ms/step - loss: 1.0643 - accuracy: 0.6291
Epoch 5/10
1563/1563 [==============================] - 29s 19ms/step - loss: 1.0172 - accuracy: 0.6463
Epoch 6/10
1563/1563 [==============================] - 30s 19ms/step - loss: 0.9782 - accuracy: 0.6600
Epoch 7/10
1563/1563 [==============================] - 30s 19ms/step - loss: 0.9527 - accuracy: 0.6694
Epoch 8/10
1563/1563 [==============================] - 30s 19ms/step - loss: 0.9269 - accuracy: 0.6787
Epoch 9/10
1563/1563 [==============================] - 30s 19ms/step - loss: 0.9028 - accuracy: 0.6864
Epoch 10/10
1563/1563 [==============================] - 26s 17ms

In [13]:
model.evaluate(x_test , y_test)

313/313 [==============================] - 4s 8ms/step - loss: 0.9699 - accuracy: 0.6658


[0.9698752760887146, 0.6657999753952026]

In [14]:
y_predicted = model.predict(x_test)

313/313 [==============================] - 1s 4ms/step


In [16]:
y_predicted = [np.argmax(i) for i in y_predicted]

In [17]:
y_predicted[:5]

[3, 8, 8, 8, 6]

In [18]:
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [19]:
from sklearn.metrics import classification_report

In [20]:
print(classification_report(y_test , y_predicted))

              precision    recall  f1-score   support

           0       0.71      0.62      0.66      1000
           1       0.86      0.69      0.77      1000
           2       0.61      0.45      0.52      1000
           3       0.48      0.54      0.51      1000
           4       0.68      0.58      0.62      1000
           5       0.56      0.61      0.58      1000
           6       0.76      0.75      0.76      1000
           7       0.74      0.72      0.73      1000
           8       0.67      0.85      0.75      1000
           9       0.66      0.84      0.74      1000

    accuracy                           0.67     10000
   macro avg       0.67      0.67      0.66     10000
weighted avg       0.67      0.67      0.66     10000

